### PR TITLE
Inclusivity v3

### PR DESCRIPTION
**Pull request by TrejGun**
take 3 on adding Inclusivity to this lib

### CODE REVIEW

**Comment by TrejGun** [comment]
as you asked, here is a commit agains new code base

**Comment by gf3** [comment]
@TrejGun why the change from `exclusive` → `inclusive`? i'd like to try to keep the APIs the same so people don't have to update their code

**Comment by TrejGun** [comment]
as I said before I'm trying to match moment.js API
https://momentjs.com/docs/#/query/is-between/
however in my code default value is `[]`

**Comment by gf3** [comment]
Closing in favour of #144

**Comment by TrejGun** [comment]
@gf3 it is #144

**Comment by gf3** [comment]
sorry, i meant #214

**Pull request closed without merging**
