### PR TITLE
Add iso-week to the named intervals

### PR DESCRIPTION
**Pull request by AndreSteenveld**
Add `isoWeek` to the set of named intervals

### CODE REVIEW

**Comment by sarates** [comment]
Page crashed when I use. Can anybody help with this?

`for (let week of range.by('isoWeek')) {`

**Comment by TristanJM** [comment]
@sarates I'll look into fixing this edge case. What use case do you have from iterating over a range by `isoWeek` as opposed to `week`?

**Comment by sarates** [comment]
No, bcs if I want to get weeks of 01.01.2017 it returns me 5 weeks, not 6. So, its a problem... Mb there is some workaround to fix this.

**Comment by TristanJM** [comment]
@sarates Simply use `range.by('week')` but on a new range with the start and end set to their isoWeeks, eg:
`
newstart = oldrange.start.startOf('isoWeek');
newend = oldrange.end.startOf('isoWeek');
range = moment.range(newstart, newend);
`

In retrospect, I'm going to remove this merge from the 3.1.0 release. I don't feel that adding `isoWeek` as an interval type serves much purpose with date ranges and instead just causes confusion.

Please let me know if you can think of a use case which couldn't be solved by a simple function like above!

**Pull request merged**
