### PR TITLE
added missing options argument for add method

### PR DESCRIPTION
**Pull request by nick-dijkshoorn**

### CODE REVIEW

**Comment by TristanJM** [comment]
Looks good, thank you! 😃

**Comment by TristanJM** [comment]
As raised by issue https://github.com/rotaready/moment-range/issues/249, we should roll this into a bigger patch to fix the `flow` & `typescript` declaration and test files:

- /lib/moment-range.d.ts ✅ 
- /lib/moment-range.js.flow
- /typing-tests/flow/moment-range.test.js 
- /typing-tests/typescript/moment-range.test.ts

This is a good time to check the rest of the library API and ensure the other declarations are correct.

**Comment by ro-savage** [comment]
@TristanJM - Anything happening with this? Do you need a new PR?

**Comment by TristanJM** [comment]
I have no problem releasing this as a quick patch (without checking/refactoring all the other definitions)

The library is very stable so we haven't been actively developing enhancements recently! We appreciate your PR though and would be more than willing to merge any other changes to the flow/ts files if you spot any 😄

**Comment by TristanJM** [comment]
@beaumontjonathan are you happy to take a look at the typescript declarations to see if any others need amending before release?

**Pull request merged**
