### PR TITLE
Add typescript definitions

### PR DESCRIPTION
**Pull request by gf3**
* Added Typescript definitions
* Added Typescript config and tests
* Added `check`, `typescript-test` npm script
* Changed `prepublish`, `preversion`, `version` scripts to support typescript definitions
* Changed CircleCI config to also run typescript tests

### CODE REVIEW

**Comment by gf3** [comment]
@hakimio they aren't released yet! you should be able to use our typings in the upcoming `4.0.0` release

**Comment by hakimio** [comment]
@gf3 I tried version-4.0.0 branch.

**Comment by gf3** [comment]
@hakimio do you have any further debug info? we have some typescript tests: https://github.com/rotaready/moment-range/blob/version-4.0.0/typing-tests/moment-range_test.ts but maybe we missed something?

**Comment by hakimio** [comment]
Here is tsconfig.json used in the project:
```
{
  "compilerOptions": {
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5",
    "sourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "skipDefaultLibCheck": true,
    "skipLibCheck": true, // Workaround for https://github.com/angular/angular/issues/17863. Remove this if you upgrade to a fixed version of Angular.
    "strict": true,
    "lib": [ "es6", "dom" ],
    "types": [ "webpack-env" ]
  },
  "exclude": [
    "bin",
    "node_modules"
  ],
  "atom": { "rewriteTsconfig": false }
}
```

I could also post auto-generated project, but then you would have to install ".NET Core SDK" to run it.

**Pull request merged**
