### PR TITLE
Handle undefined start / end for Open Ended Ranges

### PR DESCRIPTION
**Pull request by wmertens**
`== null` catches both `undefined` and `null`

If eslint complains, you may need `eqeqeq: ["error", "always", {"null": "ignore"}]`.

### CODE REVIEW

**Comment by Rhysjc** [comment]
I'm wondering if we should allow all falsey values to be passed to create an open-ended range.

@wmertens, could you try it out and see if the tests still pass?

**Comment by wmertens** [comment]
@Rhysjc did so, tests still pass but had to special-case 0 (added a test).

**Comment by Rhysjc** [comment]
@wmertens Awesome! Sorry to be a pain, could you update the README too?

**Comment by wmertens** [comment]
@Rhysjc done

**Comment by Rhysjc** [comment]
@wmertens sweet, we'll include this in the next release.

**Pull request merged**
